sudo: required
services:
    - docker

before_install:
    - docker build -t pratik151/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pratik151/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "$AWS_REGION"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "$AWS_BUCKET_NAME"
    bucket_path: "$AWS_BUCKET_PATH"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECET_KEY"