sudo: required
services:
    - docker

before_install:
    - docker build -t pratik151/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pratik151/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-698340235880"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $accesskey
    secret_access_key:
        secure: "$secretkey"