version: '3'
services: 
    web:
        build: 
            context: .
        ports: 
            - "3000:80"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true